import Container from "@/components/global/container";
import Navbar from "@/components/navbar/navbar";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@wrksz/themes/next";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", geist.variable)}
      suppressHydrationWarning>
      <body className="flex min-h-full flex-col">
        <ThemeProvider
          defaultTheme="system"
          disableTransitionOnChange>
          <ClerkProvider telemetry={false}>
            <header>
              <Navbar />
            </header>

            <main className="flex-1 py-8 md:py-12">
              <Container>{children}</Container>
            </main>

            <aside>
              <Toaster />
            </aside>
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
